"""
Módulo de configuración para AgendaTec.

Exporta las constantes principales para uso en toda la aplicación.
"""
from .constants import (
    # Estados de solicitudes
    REQUEST_STATUS_PENDING,
    REQUEST_STATUS_RESOLVED_SUCCESS,
    REQUEST_STATUS_RESOLVED_NOT_COMPLETED,
    REQUEST_STATUS_NO_SHOW,
    REQUEST_STATUS_ATTENDED_OTHER_SLOT,
    REQUEST_STATUS_CANCELED,
    REQUEST_ATTENDED_STATES,
    REQUEST_EXCLUDE_STATES,
    REQUEST_FINAL_STATES,
    REQUEST_VALID_TRANSITIONS_FROM_PENDING,
    
    # Estados de citas
    APPOINTMENT_STATUS_SCHEDULED,
    APPOINTMENT_STATUS_DONE,
    APPOINTMENT_STATUS_NO_SHOW,
    APPOINTMENT_STATUS_CANCELED,
    APPOINTMENT_VALID_STATUSES,
    
    # Tipos de solicitud
    REQUEST_TYPE_DROP,
    REQUEST_TYPE_APPOINTMENT,
    REQUEST_VALID_TYPES,
    
    # Configuración
    DEFAULT_STAFF_PASSWORD,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    VALID_SLOT_MINUTES,
    DEFAULT_SLOT_MINUTES,
    
    # Mapeos
    REQUEST_STATUS_TITLE_MAP,
    REQUEST_TYPE_LABEL_MAP,
)

__all__ = [
    "REQUEST_STATUS_PENDING",
    "REQUEST_STATUS_RESOLVED_SUCCESS",
    "REQUEST_STATUS_RESOLVED_NOT_COMPLETED",
    "REQUEST_STATUS_NO_SHOW",
    "REQUEST_STATUS_ATTENDED_OTHER_SLOT",
    "REQUEST_STATUS_CANCELED",
    "REQUEST_ATTENDED_STATES",
    "REQUEST_EXCLUDE_STATES",
    "REQUEST_FINAL_STATES",
    "REQUEST_VALID_TRANSITIONS_FROM_PENDING",
    "APPOINTMENT_STATUS_SCHEDULED",
    "APPOINTMENT_STATUS_DONE",
    "APPOINTMENT_STATUS_NO_SHOW",
    "APPOINTMENT_STATUS_CANCELED",
    "APPOINTMENT_VALID_STATUSES",
    "REQUEST_TYPE_DROP",
    "REQUEST_TYPE_APPOINTMENT",
    "REQUEST_VALID_TYPES",
    "DEFAULT_STAFF_PASSWORD",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "VALID_SLOT_MINUTES",
    "DEFAULT_SLOT_MINUTES",
    "REQUEST_STATUS_TITLE_MAP",
    "REQUEST_TYPE_LABEL_MAP",
]
