"""add inventory models to helpdesk

Revision ID: 1a277b844d1a
Revises: 3d929fb9f54c
Create Date: 2025-10-17 10:37:58.750914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a277b844d1a'
down_revision = '3d929fb9f54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_specs', sa.Boolean(), nullable=False),
    sa.Column('spec_template', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('inventory_prefix', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_inventory_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_categories_code'), ['code'], unique=True)
        batch_op.create_index('ix_inventory_categories_active_order', ['is_active', 'display_order'], unique=False)

    op.create_table('helpdesk_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('location_detail', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('maintenance_frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registered_by_id', sa.BigInteger(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk_inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['deactivated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_inventory_number'), ['inventory_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_status'), ['status'], unique=False)
        batch_op.create_index('ix_inventory_items_category', ['category_id', 'is_active'], unique=False)
        batch_op.create_index('ix_inventory_items_dept_active', ['department_id', 'is_active'], unique=False)
        batch_op.create_index('ix_inventory_items_status_active', ['status', 'is_active'], unique=False)
        batch_op.create_index('ix_inventory_items_user_active', ['assigned_to_user_id', 'is_active'], unique=False)

    op.create_table('helpdesk_inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_ticket_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['helpdesk_inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_inventory_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_history_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_history_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_inventory_history_event_timestamp', ['event_type', 'timestamp'], unique=False)
        batch_op.create_index('ix_inventory_history_item_timestamp', ['item_id', 'timestamp'], unique=False)

    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_item_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_foreign_key(None, 'helpdesk_inventory_items', ['inventory_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_inventory_item_id'))
        batch_op.drop_column('inventory_item_id')

    with op.batch_alter_table('helpdesk_inventory_history', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_history_item_timestamp')
        batch_op.drop_index('ix_inventory_history_event_timestamp')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_history_item_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_history_event_type'))

    op.drop_table('helpdesk_inventory_history')
    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_items_user_active')
        batch_op.drop_index('ix_inventory_items_status_active')
        batch_op.drop_index('ix_inventory_items_dept_active')
        batch_op.drop_index('ix_inventory_items_category')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_status'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_serial_number'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_is_active'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_inventory_number'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_department_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_assigned_to_user_id'))

    op.drop_table('helpdesk_inventory_items')
    with op.batch_alter_table('helpdesk_inventory_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_categories_active_order')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_categories_code'))

    op.drop_table('helpdesk_inventory_categories')
    # ### end Alembic commands ###
