"""add models to new app 'VisteTec'

Revision ID: 22cfcc00d729
Revises: a1b2c3d4e5f6
Create Date: 2026-02-05 10:21:21.225934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cfcc00d729'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vistetec_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vistetec_pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('current_stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vistetec_pantry_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requested_item_id', sa.Integer(), nullable=True),
    sa.Column('goal_quantity', sa.Integer(), nullable=True),
    sa.Column('collected_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['requested_item_id'], ['vistetec_pantry_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vistetec_garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'available'"), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('donated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('received_by_id', sa.BigInteger(), nullable=True),
    sa.Column('registered_by_id', sa.BigInteger(), nullable=True),
    sa.Column('delivered_to_id', sa.BigInteger(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['delivered_to_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['donated_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistetec_garments', schema=None) as batch_op:
        batch_op.create_index('ix_vistetec_garment_gender_size', ['gender', 'size'], unique=False)
        batch_op.create_index('ix_vistetec_garment_status_category', ['status', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_garments_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_garments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_vistetec_garments_status'), ['status'], unique=False)

    op.create_table('vistetec_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_appointments', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_appointments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['vistetec_locations.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistetec_time_slots', schema=None) as batch_op:
        batch_op.create_index('ix_vistetec_slot_date_active', ['date', 'is_active'], unique=False)
        batch_op.create_index('ix_vistetec_slot_volunteer_date', ['volunteer_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_time_slots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_time_slots_volunteer_id'), ['volunteer_id'], unique=False)

    op.create_table('vistetec_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attended_by_id', sa.BigInteger(), nullable=True),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['attended_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['vistetec_garments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['vistetec_locations.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['vistetec_time_slots.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistetec_appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vistetec_appointments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_vistetec_appointments_garment_id'), ['garment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_appointments_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_vistetec_appt_garment_status', ['garment_id', 'status'], unique=False)
        batch_op.create_index('ix_vistetec_appt_student_status', ['student_id', 'status'], unique=False)

    op.create_table('vistetec_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('donor_id', sa.BigInteger(), nullable=True),
    sa.Column('donor_name', sa.String(length=100), nullable=True),
    sa.Column('donation_type', sa.String(length=20), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=True),
    sa.Column('pantry_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('registered_by_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['garment_id'], ['vistetec_garments.id'], ),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['vistetec_pantry_items.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistetec_donations', schema=None) as batch_op:
        batch_op.create_index('ix_vistetec_donation_donor', ['donor_id'], unique=False)
        batch_op.create_index('ix_vistetec_donation_type', ['donation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vistetec_donations_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistetec_donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistetec_donations_code'))
        batch_op.drop_index('ix_vistetec_donation_type')
        batch_op.drop_index('ix_vistetec_donation_donor')

    op.drop_table('vistetec_donations')
    with op.batch_alter_table('vistetec_appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_vistetec_appt_student_status')
        batch_op.drop_index('ix_vistetec_appt_garment_status')
        batch_op.drop_index(batch_op.f('ix_vistetec_appointments_student_id'))
        batch_op.drop_index(batch_op.f('ix_vistetec_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_vistetec_appointments_garment_id'))
        batch_op.drop_index(batch_op.f('ix_vistetec_appointments_code'))

    op.drop_table('vistetec_appointments')
    with op.batch_alter_table('vistetec_time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistetec_time_slots_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_vistetec_time_slots_date'))
        batch_op.drop_index('ix_vistetec_slot_volunteer_date')
        batch_op.drop_index('ix_vistetec_slot_date_active')

    op.drop_table('vistetec_time_slots')
    with op.batch_alter_table('vistetec_garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistetec_garments_status'))
        batch_op.drop_index(batch_op.f('ix_vistetec_garments_code'))
        batch_op.drop_index(batch_op.f('ix_vistetec_garments_category'))
        batch_op.drop_index('ix_vistetec_garment_status_category')
        batch_op.drop_index('ix_vistetec_garment_gender_size')

    op.drop_table('vistetec_garments')
    op.drop_table('vistetec_pantry_campaigns')
    op.drop_table('vistetec_pantry_items')
    op.drop_table('vistetec_locations')
    # ### end Alembic commands ###
