"""add_celery_task_models

Revision ID: 2c0b6910e578
Revises: 7fa648012dfc
Create Date: 2026-03-12 08:21:13.148298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c0b6910e578'
down_revision = '7fa648012dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_task_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_args', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_name')
    )
    op.create_index(op.f('ix_core_task_definitions_app_name'), 'core_task_definitions', ['app_name'], unique=False)
    op.create_table('core_periodic_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('args_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('kwargs_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_name'], ['core_task_definitions.task_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_core_periodic_tasks_is_active'), 'core_periodic_tasks', ['is_active'], unique=False)
    op.create_table('core_task_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=36), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('triggered_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('periodic_task_id', sa.Integer(), nullable=True),
    sa.Column('args_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodic_task_id'], ['core_periodic_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['core_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_task_runs_celery_task_id'), 'core_task_runs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_core_task_runs_created_at'), 'core_task_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_core_task_runs_status'), 'core_task_runs', ['status'], unique=False)
    op.create_index(op.f('ix_core_task_runs_task_name'), 'core_task_runs', ['task_name'], unique=False)
    op.create_index('ix_task_runs_status_created', 'core_task_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_task_runs_task_name_created', 'core_task_runs', ['task_name', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_runs_task_name_created', table_name='core_task_runs')
    op.drop_index('ix_task_runs_status_created', table_name='core_task_runs')
    op.drop_index(op.f('ix_core_task_runs_task_name'), table_name='core_task_runs')
    op.drop_index(op.f('ix_core_task_runs_status'), table_name='core_task_runs')
    op.drop_index(op.f('ix_core_task_runs_created_at'), table_name='core_task_runs')
    op.drop_index(op.f('ix_core_task_runs_celery_task_id'), table_name='core_task_runs')
    op.drop_table('core_task_runs')
    op.drop_index(op.f('ix_core_periodic_tasks_is_active'), table_name='core_periodic_tasks')
    op.drop_table('core_periodic_tasks')
    op.drop_index(op.f('ix_core_task_definitions_app_name'), table_name='core_task_definitions')
    op.drop_table('core_task_definitions')
    # ### end Alembic commands ###
