"""add updated_at to notifications and assignments

Revision ID: 2faa82f9e4a5
Revises: c4c62c523416
Create Date: 2025-11-27 13:07:30.606595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faa82f9e4a5'
down_revision = 'c4c62c523416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('helpdesk_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_assignment', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('core_notifications', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
