"""add_icon_deparment

Revision ID: 3755f73d1b89
Revises: a3b72f4eee6e
Create Date: 2025-10-09 16:50:05.511240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3755f73d1b89'
down_revision = 'a3b72f4eee6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_class', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('icon_class')

    # ### end Alembic commands ###
