"""add_models_helpdesk

Revision ID: 3da89d70c026
Revises: 5a5afd7209e8
Create Date: 2025-10-08 12:10:41.810022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da89d70c026'
down_revision = '5a5afd7209e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_category', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_category_area_active', ['area', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_category_code'), ['code'], unique=True)

    op.create_table('helpdesk_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_department_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('office_document_folio', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_to_team', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('time_invested_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk_category.id'], ),
    sa.ForeignKeyConstraint(['requester_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_area'), ['area'], unique=False)
        batch_op.create_index('ix_helpdesk_ticket_area_status', ['area', 'status'], unique=False)
        batch_op.create_index('ix_helpdesk_ticket_assigned_status', ['assigned_to_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index('ix_helpdesk_ticket_requester_status', ['requester_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_status'), ['status'], unique=False)
        batch_op.create_index('ix_helpdesk_ticket_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('helpdesk_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_to_team', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_assignment_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('helpdesk_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('auto_delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_attachment', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_attachment_auto_delete', ['auto_delete_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_attachment_auto_delete_at'), ['auto_delete_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_attachment_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('helpdesk_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_comment', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_comment_ticket_created', ['ticket_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_comment_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('helpdesk_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_status_log', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_status_log_ticket_created', ['ticket_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_status_log_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_status_log_ticket_id'))
        batch_op.drop_index('ix_helpdesk_status_log_ticket_created')

    op.drop_table('helpdesk_status_log')
    with op.batch_alter_table('helpdesk_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_comment_ticket_id'))
        batch_op.drop_index('ix_helpdesk_comment_ticket_created')

    op.drop_table('helpdesk_comment')
    with op.batch_alter_table('helpdesk_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_attachment_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_attachment_auto_delete_at'))
        batch_op.drop_index('ix_helpdesk_attachment_auto_delete')

    op.drop_table('helpdesk_attachment')
    with op.batch_alter_table('helpdesk_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_assignment_ticket_id'))

    op.drop_table('helpdesk_assignment')
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_ticket_number'))
        batch_op.drop_index('ix_helpdesk_ticket_status_priority')
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_status'))
        batch_op.drop_index('ix_helpdesk_ticket_requester_status')
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_requester_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_created_at'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_assigned_to_user_id'))
        batch_op.drop_index('ix_helpdesk_ticket_assigned_status')
        batch_op.drop_index('ix_helpdesk_ticket_area_status')
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_area'))

    op.drop_table('helpdesk_ticket')
    with op.batch_alter_table('helpdesk_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_category_code'))
        batch_op.drop_index('ix_helpdesk_category_area_active')

    op.drop_table('helpdesk_category')
    # ### end Alembic commands ###
