"""Add helpdesk_ticket_edit_log table

Revision ID: 427b52998924
Revises: 7cfe8bee2002
Create Date: 2026-01-29 10:41:06.190027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427b52998924'
down_revision = '7cfe8bee2002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_ticket_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_ticket_edit_log', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_ticket_edit_log_ticket_created', ['ticket_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_edit_log_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket_edit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_edit_log_ticket_id'))
        batch_op.drop_index('ix_helpdesk_ticket_edit_log_ticket_created')

    op.drop_table('helpdesk_ticket_edit_log')
    # ### end Alembic commands ###
