"""add_multiple_users_for_position

Revision ID: 5a5afd7209e8
Revises: 80b72446574d
Create Date: 2025-10-06 17:51:43.117383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5afd7209e8'
down_revision = '80b72446574d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allows_multiple', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('allows_multiple')

    # ### end Alembic commands ###
