"""add_email_to_postion

Revision ID: 5d3a0344652a
Revises: 3da89d70c026
Create Date: 2025-10-09 12:12:17.281090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3a0344652a'
down_revision = '3da89d70c026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_positions_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
