"""add extension to position

Revision ID: 5f96ae18f522
Revises: 1a277b844d1a
Create Date: 2025-10-29 12:11:37.426913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f96ae18f522'
down_revision = '1a277b844d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_extension', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone_notes', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('phone_notes')
        batch_op.drop_column('phone_extension')

    # ### end Alembic commands ###
