"""add to collaborators to helpdesk

Revision ID: 767d26a7980f
Revises: c785292a30ad
Create Date: 2025-11-24 14:02:07.633051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767d26a7980f'
down_revision = 'c785292a30ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_ticket_collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('collaboration_role', sa.String(length=20), nullable=False),
    sa.Column('time_invested_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('added_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'user_id', name='uq_ticket_user_collaboration')
    )
    with op.batch_alter_table('helpdesk_ticket_collaborator', schema=None) as batch_op:
        batch_op.create_index('ix_helpdesk_collaborator_ticket', ['ticket_id'], unique=False)
        batch_op.create_index('ix_helpdesk_collaborator_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_collaborator_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_collaborator_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket_collaborator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_collaborator_user_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_collaborator_ticket_id'))
        batch_op.drop_index('ix_helpdesk_collaborator_user')
        batch_op.drop_index('ix_helpdesk_collaborator_ticket')

    op.drop_table('helpdesk_ticket_collaborator')
    # ### end Alembic commands ###
