"""Add AcademicPeriod and PeriodEnabledDay models

Revision ID: 7cfe8bee2002
Revises: cf9a2d8e4b17
Create Date: 2026-01-08 14:29:43.882323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfe8bee2002'
down_revision = 'cf9a2d8e4b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tabla de períodos académicos (CORE - sin configuraciones específicas de apps)
    op.create_table('core_academic_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='period_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='check_period_dates'),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('core_academic_periods', schema=None) as batch_op:
        batch_op.create_index('idx_period_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_period_status', ['status'], unique=False)

    # Crear tabla de configuración específica de AgendaTec por período
    op.create_table('agendatec_period_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('student_admission_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_cancellations_per_student', sa.Integer(), nullable=False, server_default='2'),
    sa.Column('allow_drop_requests', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('allow_appointment_requests', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['core_academic_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id')
    )
    with op.batch_alter_table('agendatec_period_config', schema=None) as batch_op:
        batch_op.create_index('idx_agendatec_period_config_period', ['period_id'], unique=False)

    op.create_table('agendatec_period_enabled_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['core_academic_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'day', name='uq_period_day')
    )
    with op.batch_alter_table('agendatec_period_enabled_days', schema=None) as batch_op:
        batch_op.create_index('idx_period_enabled_days', ['period_id', 'day'], unique=False)

    with op.batch_alter_table('agendatec_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agendatec_requests_period_id'), ['period_id'], unique=False)
        batch_op.create_foreign_key(None, 'core_academic_periods', ['period_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('agendatec_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agendatec_requests_period_id'))
        batch_op.drop_column('period_id')

    with op.batch_alter_table('agendatec_period_enabled_days', schema=None) as batch_op:
        batch_op.drop_index('idx_period_enabled_days')

    op.drop_table('agendatec_period_enabled_days')

    # Eliminar tabla de configuración de AgendaTec
    with op.batch_alter_table('agendatec_period_config', schema=None) as batch_op:
        batch_op.drop_index('idx_agendatec_period_config_period')

    op.drop_table('agendatec_period_config')

    with op.batch_alter_table('core_academic_periods', schema=None) as batch_op:
        batch_op.drop_index('idx_period_status')
        batch_op.drop_index('idx_period_dates')

    op.drop_table('core_academic_periods')
    # ### end Alembic commands ###
