"""add_global_warehouse_module

Revision ID: 7fa648012dfc
Revises: b3c5d7e9f1a3
Create Date: 2026-03-09 11:50:20.648509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa648012dfc'
down_revision = 'b3c5d7e9f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("'bi-box-seam'"), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouse_categories_dept_active', 'warehouse_categories', ['department_code', 'is_active'], unique=False)
    op.create_table('warehouse_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['warehouse_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_warehouse_subcategories_cat_name')
    )
    op.create_index('ix_warehouse_subcategories_cat_active', 'warehouse_subcategories', ['category_id', 'is_active'], unique=False)
    op.create_table('warehouse_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('department_code', sa.String(length=50), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("'bi-box'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('restock_point_auto', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('restock_point_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restock_lead_time_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('last_restock_calc_at', sa.DateTime(), nullable=True),
    sa.Column('restock_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['warehouse_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_warehouse_products_code', 'warehouse_products', ['code'], unique=False)
    op.create_index('ix_warehouse_products_dept_active', 'warehouse_products', ['department_code', 'is_active'], unique=False)
    op.create_index('ix_warehouse_products_subcategory_active', 'warehouse_products', ['subcategory_id', 'is_active'], unique=False)
    op.create_table('warehouse_stock_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_folio', sa.String(length=100), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('registered_by_id', sa.BigInteger(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_exhausted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('voided', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('voided_by_id', sa.BigInteger(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_products.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouse_stock_entries_product_date', 'warehouse_stock_entries', ['product_id', 'purchase_date'], unique=False)
    op.create_index('ix_warehouse_stock_entries_product_status', 'warehouse_stock_entries', ['product_id', 'is_exhausted', 'voided'], unique=False)
    op.create_table('warehouse_ticket_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_app', sa.String(length=30), nullable=False),
    sa.Column('source_ticket_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_by_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_app', 'source_ticket_id', 'product_id', name='uq_warehouse_ticket_materials')
    )
    op.create_index('ix_warehouse_ticket_materials_product', 'warehouse_ticket_materials', ['product_id'], unique=False)
    op.create_index('ix_warehouse_ticket_materials_source', 'warehouse_ticket_materials', ['source_app', 'source_ticket_id'], unique=False)
    op.create_table('warehouse_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source_app', sa.String(length=30), nullable=True),
    sa.Column('source_ticket_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['warehouse_stock_entries.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['warehouse_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warehouse_movements_product_at', 'warehouse_movements', ['product_id', 'performed_at'], unique=False)
    op.create_index('ix_warehouse_movements_source', 'warehouse_movements', ['source_app', 'source_ticket_id'], unique=False)
    op.create_index('ix_warehouse_movements_type_at', 'warehouse_movements', ['movement_type', 'performed_at'], unique=False)
    op.alter_column('core_users', 'control_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_helpdesk_inventory_items_id_tecnm'), 'helpdesk_inventory_items', type_='unique')
    op.drop_constraint(op.f('uq_helpdesk_inventory_items_itcj_serial'), 'helpdesk_inventory_items', type_='unique')
    op.drop_index(op.f('ix_helpdesk_inventory_items_id_tecnm'), table_name='helpdesk_inventory_items')
    op.create_index(op.f('ix_helpdesk_inventory_items_id_tecnm'), 'helpdesk_inventory_items', ['id_tecnm'], unique=True)
    op.drop_index(op.f('ix_helpdesk_inventory_items_itcj_serial'), table_name='helpdesk_inventory_items')
    op.create_index(op.f('ix_helpdesk_inventory_items_itcj_serial'), 'helpdesk_inventory_items', ['itcj_serial'], unique=True)
    op.drop_index(op.f('ix_retirement_request_items_item'), table_name='helpdesk_inventory_retirement_request_items')
    op.drop_index(op.f('ix_retirement_request_items_request'), table_name='helpdesk_inventory_retirement_request_items')
    op.create_index(op.f('ix_helpdesk_inventory_retirement_request_items_item_id'), 'helpdesk_inventory_retirement_request_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_inventory_retirement_request_items_request_id'), 'helpdesk_inventory_retirement_request_items', ['request_id'], unique=False)
    op.drop_constraint(op.f('helpdesk_inventory_retirement_requests_folio_key'), 'helpdesk_inventory_retirement_requests', type_='unique')
    op.drop_index(op.f('ix_retirement_requests_by'), table_name='helpdesk_inventory_retirement_requests')
    op.drop_index(op.f('ix_retirement_requests_folio'), table_name='helpdesk_inventory_retirement_requests')
    op.drop_index(op.f('ix_retirement_requests_status'), table_name='helpdesk_inventory_retirement_requests')
    op.create_index(op.f('ix_helpdesk_inventory_retirement_requests_folio'), 'helpdesk_inventory_retirement_requests', ['folio'], unique=True)
    op.create_index(op.f('ix_helpdesk_inventory_retirement_requests_requested_by_id'), 'helpdesk_inventory_retirement_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_helpdesk_inventory_retirement_requests_status'), 'helpdesk_inventory_retirement_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helpdesk_inventory_retirement_requests_status'), table_name='helpdesk_inventory_retirement_requests')
    op.drop_index(op.f('ix_helpdesk_inventory_retirement_requests_requested_by_id'), table_name='helpdesk_inventory_retirement_requests')
    op.drop_index(op.f('ix_helpdesk_inventory_retirement_requests_folio'), table_name='helpdesk_inventory_retirement_requests')
    op.create_index(op.f('ix_retirement_requests_status'), 'helpdesk_inventory_retirement_requests', ['status'], unique=False)
    op.create_index(op.f('ix_retirement_requests_folio'), 'helpdesk_inventory_retirement_requests', ['folio'], unique=False)
    op.create_index(op.f('ix_retirement_requests_by'), 'helpdesk_inventory_retirement_requests', ['requested_by_id'], unique=False)
    op.create_unique_constraint(op.f('helpdesk_inventory_retirement_requests_folio_key'), 'helpdesk_inventory_retirement_requests', ['folio'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_helpdesk_inventory_retirement_request_items_request_id'), table_name='helpdesk_inventory_retirement_request_items')
    op.drop_index(op.f('ix_helpdesk_inventory_retirement_request_items_item_id'), table_name='helpdesk_inventory_retirement_request_items')
    op.create_index(op.f('ix_retirement_request_items_request'), 'helpdesk_inventory_retirement_request_items', ['request_id'], unique=False)
    op.create_index(op.f('ix_retirement_request_items_item'), 'helpdesk_inventory_retirement_request_items', ['item_id'], unique=False)
    op.drop_index(op.f('ix_helpdesk_inventory_items_itcj_serial'), table_name='helpdesk_inventory_items')
    op.create_index(op.f('ix_helpdesk_inventory_items_itcj_serial'), 'helpdesk_inventory_items', ['itcj_serial'], unique=False)
    op.drop_index(op.f('ix_helpdesk_inventory_items_id_tecnm'), table_name='helpdesk_inventory_items')
    op.create_index(op.f('ix_helpdesk_inventory_items_id_tecnm'), 'helpdesk_inventory_items', ['id_tecnm'], unique=False)
    op.create_unique_constraint(op.f('uq_helpdesk_inventory_items_itcj_serial'), 'helpdesk_inventory_items', ['itcj_serial'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_helpdesk_inventory_items_id_tecnm'), 'helpdesk_inventory_items', ['id_tecnm'], postgresql_nulls_not_distinct=False)
    op.alter_column('core_users', 'control_number',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_index('ix_warehouse_movements_type_at', table_name='warehouse_movements')
    op.drop_index('ix_warehouse_movements_source', table_name='warehouse_movements')
    op.drop_index('ix_warehouse_movements_product_at', table_name='warehouse_movements')
    op.drop_table('warehouse_movements')
    op.drop_index('ix_warehouse_ticket_materials_source', table_name='warehouse_ticket_materials')
    op.drop_index('ix_warehouse_ticket_materials_product', table_name='warehouse_ticket_materials')
    op.drop_table('warehouse_ticket_materials')
    op.drop_index('ix_warehouse_stock_entries_product_status', table_name='warehouse_stock_entries')
    op.drop_index('ix_warehouse_stock_entries_product_date', table_name='warehouse_stock_entries')
    op.drop_table('warehouse_stock_entries')
    op.drop_index('ix_warehouse_products_subcategory_active', table_name='warehouse_products')
    op.drop_index('ix_warehouse_products_dept_active', table_name='warehouse_products')
    op.drop_index('ix_warehouse_products_code', table_name='warehouse_products')
    op.drop_table('warehouse_products')
    op.drop_index('ix_warehouse_subcategories_cat_active', table_name='warehouse_subcategories')
    op.drop_table('warehouse_subcategories')
    op.drop_index('ix_warehouse_categories_dept_active', table_name='warehouse_categories')
    op.drop_table('warehouse_categories')
    # ### end Alembic commands ###
