"""add to creator and updater to ticket and user

Revision ID: 8961531fbe52
Revises: 2faa82f9e4a5
Create Date: 2025-12-02 10:48:14.713165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8961531fbe52'
down_revision = '2faa82f9e4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_id', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key('fk_helpdesk_ticket_created_by', 'core_users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_helpdesk_ticket_updated_by', 'core_users', ['updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_helpdesk_ticket_updated_by', type_='foreignkey')
        batch_op.drop_constraint('fk_helpdesk_ticket_created_by', type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
