"""Add core_themes table

Revision ID: 955c64adde31
Revises: 427b52998924
Create Date: 2026-02-03 09:42:04.474632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '955c64adde31'
down_revision = '427b52998924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('is_manually_active', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=False),
    sa.Column('decorations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('css_file', sa.String(length=255), nullable=True),
    sa.Column('js_file', sa.String(length=255), nullable=True),
    sa.Column('preview_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_themes_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_themes_name'))

    op.drop_table('core_themes')
    # ### end Alembic commands ###
