"""notifications global

Revision ID: 9ece8fd65ce8
Revises: 757969626448
Create Date: 2025-10-29 14:06:48.429867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ece8fd65ce8'
down_revision = '757969626448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_key'))
        batch_op.create_index(batch_op.f('ix_core_apps_key'), ['key'], unique=True)

    with op.batch_alter_table('core_notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=postgresql.ENUM('APPOINTMENT_CREATED', 'APPOINTMENT_CANCELED', 'REQUEST_STATUS_CHANGED', 'DROP_CREATED', 'SYSTEM', name='notif_type_enum'),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_core_notifications_app_type'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_user_app'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_user_unread'))
        batch_op.create_index(batch_op.f('ix_core_notifications_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_app_type', ['app_name', 'type'], unique=False)
        batch_op.create_index('ix_notifications_user_app', ['user_id', 'app_name'], unique=False)
        batch_op.create_index('ix_notifications_user_unread', ['user_id', 'is_read'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_notifications_request'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_appointment'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_program'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notifications_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'agendatec_requests', ['source_request_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'agendatec_appointments', ['source_appointment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'core_programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'core_users', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('core_position_app_perms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_position_app_perms_position_app'))
        batch_op.create_index('ix_position_app_perms_position_app', ['position_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_position_app_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_position_app_roles_position_app'))
        batch_op.create_index('ix_position_app_roles_position_app', ['position_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_code'))
        batch_op.drop_index(batch_op.f('ix_positions_email'))
        batch_op.create_index(batch_op.f('ix_core_positions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_core_positions_email'), ['email'], unique=True)

    with op.batch_alter_table('core_user_app_perms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_user_app_perms_user_app'))
        batch_op.create_index('ix_user_app_perms_user_app', ['user_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_user_app_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_user_app_roles_user_app'))
        batch_op.create_index('ix_user_app_roles_user_app', ['user_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_user_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_user_positions_active'))
        batch_op.drop_index(batch_op.f('ix_user_positions_position_id'))
        batch_op.drop_index(batch_op.f('ix_user_positions_user_id'))
        batch_op.create_index(batch_op.f('ix_core_user_positions_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_user_positions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_positions_active', ['user_id', 'position_id', 'is_active'], unique=False)

    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_users_control_number'))
        batch_op.drop_index(batch_op.f('ix_core_users_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_control_number'), ['control_number'], unique=False)

    with op.batch_alter_table('core_user_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_positions_active')
        batch_op.drop_index(batch_op.f('ix_core_user_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_user_positions_position_id'))
        batch_op.create_index(batch_op.f('ix_user_positions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_positions_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_user_positions_active'), ['user_id', 'position_id', 'is_active'], unique=False)

    with op.batch_alter_table('core_user_app_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_user_app_roles_user_app')
        batch_op.create_index(batch_op.f('ix_core_user_app_roles_user_app'), ['user_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_user_app_perms', schema=None) as batch_op:
        batch_op.drop_index('ix_user_app_perms_user_app')
        batch_op.create_index(batch_op.f('ix_core_user_app_perms_user_app'), ['user_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_positions_email'))
        batch_op.drop_index(batch_op.f('ix_core_positions_code'))
        batch_op.create_index(batch_op.f('ix_positions_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_positions_code'), ['code'], unique=True)

    with op.batch_alter_table('core_position_app_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_position_app_roles_position_app')
        batch_op.create_index(batch_op.f('ix_core_position_app_roles_position_app'), ['position_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_position_app_perms', schema=None) as batch_op:
        batch_op.drop_index('ix_position_app_perms_position_app')
        batch_op.create_index(batch_op.f('ix_core_position_app_perms_position_app'), ['position_id', 'app_id'], unique=False)

    with op.batch_alter_table('core_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user'), 'core_users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_program'), 'core_programs', ['program_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_appointment'), 'agendatec_appointments', ['source_appointment_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_request'), 'agendatec_requests', ['source_request_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.drop_index('ix_notifications_user_unread')
        batch_op.drop_index('ix_notifications_user_app')
        batch_op.drop_index('ix_notifications_app_type')
        batch_op.drop_index(batch_op.f('ix_core_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_core_notifications_app_name'))
        batch_op.create_index(batch_op.f('ix_core_notifications_user_unread'), ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_user_app'), ['user_id', 'app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_notifications_app_type'), ['app_name', 'type'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('APPOINTMENT_CREATED', 'APPOINTMENT_CANCELED', 'REQUEST_STATUS_CHANGED', 'DROP_CREATED', 'SYSTEM', name='notif_type_enum'),
               existing_nullable=False)

    with op.batch_alter_table('core_apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_apps_key'))
        batch_op.create_index(batch_op.f('ix_apps_key'), ['key'], unique=True)

    # ### end Alembic commands ###
