"""add custom fields support to helpdesk

Revision ID: cf9a2d8e4b17
Revises: c4c62c523416
Create Date: 2025-12-11 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9a2d8e4b17'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add field_template JSON column to helpdesk_category
    with op.batch_alter_table('helpdesk_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_template', sa.JSON(), nullable=True))

    # Add custom_fields JSON column to helpdesk_ticket
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    with op.batch_alter_table('helpdesk_category', schema=None) as batch_op:
        batch_op.drop_column('field_template')

    # ### end Alembic commands ###
