"""add groups to inventory

Revision ID: be5248168cc0
Revises: e8659dac8ba3
Create Date: 2025-11-18 09:48:44.240339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5248168cc0'
down_revision = 'e8659dac8ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_inventory_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('location_notes', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['core_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'department_id', name='uq_group_name_per_dept')
    )
    with op.batch_alter_table('helpdesk_inventory_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_groups_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_groups_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_groups_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_inventory_groups_dept_active', ['department_id', 'is_active'], unique=False)

    op.create_table('helpdesk_inventory_group_capacities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['helpdesk_inventory_categories.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['helpdesk_inventory_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'category_id', name='uq_group_category')
    )
    with op.batch_alter_table('helpdesk_inventory_group_capacities', schema=None) as batch_op:
        batch_op.create_index('ix_group_capacities_group', ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_group_capacities_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_group_capacities_group_id'), ['group_id'], unique=False)

    op.create_table('helpdesk_ticket_inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['helpdesk_inventory_items.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['helpdesk_ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'inventory_item_id', name='uq_ticket_item')
    )
    with op.batch_alter_table('helpdesk_ticket_inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_inventory_items_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_inventory_items_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index('ix_ticket_inventory_item', ['inventory_item_id'], unique=False)
        batch_op.create_index('ix_ticket_inventory_ticket', ['ticket_id'], unique=False)

    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_items_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key(None, 'helpdesk_inventory_groups', ['group_id'], ['id'])

    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_inventory_item_id'))
        batch_op.drop_constraint(batch_op.f('helpdesk_ticket_inventory_item_id_fkey'), type_='foreignkey')
        batch_op.drop_column('inventory_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('helpdesk_ticket_inventory_item_id_fkey'), 'helpdesk_inventory_items', ['inventory_item_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_helpdesk_ticket_inventory_item_id'), ['inventory_item_id'], unique=False)

    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_items_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('helpdesk_ticket_inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_inventory_ticket')
        batch_op.drop_index('ix_ticket_inventory_item')
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_inventory_items_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_ticket_inventory_items_inventory_item_id'))

    op.drop_table('helpdesk_ticket_inventory_items')
    with op.batch_alter_table('helpdesk_inventory_group_capacities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_group_capacities_group_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_group_capacities_category_id'))
        batch_op.drop_index('ix_group_capacities_group')

    op.drop_table('helpdesk_inventory_group_capacities')
    with op.batch_alter_table('helpdesk_inventory_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_groups_dept_active')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_groups_is_active'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_groups_department_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_groups_code'))

    op.drop_table('helpdesk_inventory_groups')
    # ### end Alembic commands ###
