"""update_ticket_rating_to_survey_fields

Revision ID: c4c62c523416
Revises: 767d26a7980f
Create Date: 2025-11-26 08:48:20.253289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c62c523416'
down_revision = '767d26a7980f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_attention', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_efficiency', sa.Boolean(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('rating_efficiency')
        batch_op.drop_column('rating_speed')
        batch_op.drop_column('rating_attention')

    # ### end Alembic commands ###
