"""add created_at to inventory item

Revision ID: c785292a30ad
Revises: be5248168cc0
Create Date: 2025-11-20 09:53:17.571576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c785292a30ad'
down_revision = 'be5248168cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
