"""add verification to inventory

Revision ID: cebd1b61e623
Revises: k4m6n8p2r4t6
Create Date: 2026-03-02 11:41:15.369124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebd1b61e623'
down_revision = 'k4m6n8p2r4t6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_inventory_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_id', sa.BigInteger(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('location_confirmed', sa.String(length=200), nullable=True),
    sa.Column('status_found', sa.String(length=30), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('changes_applied', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['helpdesk_inventory_items.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_inventory_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_verifications_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_verifications_verified_at'), ['verified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_helpdesk_inventory_verifications_verified_by_id'), ['verified_by_id'], unique=False)
        batch_op.create_index('ix_inv_verif_item_at', ['inventory_item_id', 'verified_at'], unique=False)
        batch_op.create_index('ix_inv_verif_user_at', ['verified_by_id', 'verified_at'], unique=False)

    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_verified_by_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'core_users', ['last_verified_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_verified_by_id')
        batch_op.drop_column('last_verified_at')

    with op.batch_alter_table('helpdesk_inventory_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_verif_user_at')
        batch_op.drop_index('ix_inv_verif_item_at')
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_verifications_verified_by_id'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_verifications_verified_at'))
        batch_op.drop_index(batch_op.f('ix_helpdesk_inventory_verifications_inventory_item_id'))

    op.drop_table('helpdesk_inventory_verifications')
    # ### end Alembic commands ###
