"""add_maintenance_app

Revision ID: d50f3d9281f2
Revises: 2c0b6910e578
Create Date: 2026-03-20 14:00:55.350538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50f3d9281f2'
down_revision = '2c0b6910e578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maint_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("'bi-tools'"), nullable=False),
    sa.Column('field_template', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_maint_categories_active_order', 'maint_categories', ['is_active', 'display_order'], unique=False)
    op.create_table('maint_technician_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('area_code', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_tech_area_code', 'maint_technician_areas', ['area_code'], unique=False)
    op.create_index('ix_maint_tech_area_user', 'maint_technician_areas', ['user_id'], unique=False)
    op.create_index('ix_maint_tech_area_user_code', 'maint_technician_areas', ['user_id', 'area_code'], unique=True)
    op.create_table('maint_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_department_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=20), nullable=True),
    sa.Column('service_origin', sa.String(length=20), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('time_invested_minutes', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('rating_attention', sa.Integer(), nullable=True),
    sa.Column('rating_speed', sa.Integer(), nullable=True),
    sa.Column('rating_efficiency', sa.Boolean(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by_id', sa.BigInteger(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canceled_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['maint_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['requester_department_id'], ['core_departments.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index('ix_maint_tickets_category_status', 'maint_tickets', ['category_id', 'status'], unique=False)
    op.create_index('ix_maint_tickets_due_at', 'maint_tickets', ['due_at'], unique=False)
    op.create_index('ix_maint_tickets_number', 'maint_tickets', ['ticket_number'], unique=False)
    op.create_index('ix_maint_tickets_requester_status', 'maint_tickets', ['requester_id', 'status'], unique=False)
    op.create_index('ix_maint_tickets_resolved_by', 'maint_tickets', ['resolved_by_id'], unique=False)
    op.create_index('ix_maint_tickets_status_created', 'maint_tickets', ['status', 'created_at'], unique=False)
    op.create_table('maint_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maint_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_comment_ticket_date', 'maint_comments', ['ticket_id', 'created_at'], unique=False)
    op.create_table('maint_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maint_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_status_log_ticket_date', 'maint_status_logs', ['ticket_id', 'created_at'], unique=False)
    op.create_index('ix_maint_status_log_user_date', 'maint_status_logs', ['changed_by_id', 'created_at'], unique=False)
    op.create_table('maint_ticket_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('performed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maint_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_action_log_action_date', 'maint_ticket_action_logs', ['action', 'performed_at'], unique=False)
    op.create_index('ix_maint_action_log_ticket_date', 'maint_ticket_action_logs', ['ticket_id', 'performed_at'], unique=False)
    op.create_index('ix_maint_action_log_user_date', 'maint_ticket_action_logs', ['performed_by_id', 'performed_at'], unique=False)
    op.create_table('maint_ticket_technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('unassigned_by_id', sa.BigInteger(), nullable=True),
    sa.Column('unassigned_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maint_tickets.id'], ),
    sa.ForeignKeyConstraint(['unassigned_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_ticket_tech_active', 'maint_ticket_technicians', ['ticket_id', 'unassigned_at'], unique=False)
    op.create_index('ix_maint_ticket_tech_history', 'maint_ticket_technicians', ['ticket_id', 'assigned_at'], unique=False)
    op.create_index('ix_maint_ticket_tech_user_active', 'maint_ticket_technicians', ['user_id', 'unassigned_at'], unique=False)
    op.create_table('maint_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('auto_delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['maint_comments.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['maint_tickets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_attachment_auto_delete', 'maint_attachments', ['auto_delete_at'], unique=False)
    op.create_index('ix_maint_attachment_ticket_type', 'maint_attachments', ['ticket_id', 'attachment_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maint_attachment_ticket_type', table_name='maint_attachments')
    op.drop_index('ix_maint_attachment_auto_delete', table_name='maint_attachments')
    op.drop_table('maint_attachments')
    op.drop_index('ix_maint_ticket_tech_user_active', table_name='maint_ticket_technicians')
    op.drop_index('ix_maint_ticket_tech_history', table_name='maint_ticket_technicians')
    op.drop_index('ix_maint_ticket_tech_active', table_name='maint_ticket_technicians')
    op.drop_table('maint_ticket_technicians')
    op.drop_index('ix_maint_action_log_user_date', table_name='maint_ticket_action_logs')
    op.drop_index('ix_maint_action_log_ticket_date', table_name='maint_ticket_action_logs')
    op.drop_index('ix_maint_action_log_action_date', table_name='maint_ticket_action_logs')
    op.drop_table('maint_ticket_action_logs')
    op.drop_index('ix_maint_status_log_user_date', table_name='maint_status_logs')
    op.drop_index('ix_maint_status_log_ticket_date', table_name='maint_status_logs')
    op.drop_table('maint_status_logs')
    op.drop_index('ix_maint_comment_ticket_date', table_name='maint_comments')
    op.drop_table('maint_comments')
    op.drop_index('ix_maint_tickets_status_created', table_name='maint_tickets')
    op.drop_index('ix_maint_tickets_resolved_by', table_name='maint_tickets')
    op.drop_index('ix_maint_tickets_requester_status', table_name='maint_tickets')
    op.drop_index('ix_maint_tickets_number', table_name='maint_tickets')
    op.drop_index('ix_maint_tickets_due_at', table_name='maint_tickets')
    op.drop_index('ix_maint_tickets_category_status', table_name='maint_tickets')
    op.drop_table('maint_tickets')
    op.drop_index('ix_maint_tech_area_user_code', table_name='maint_technician_areas')
    op.drop_index('ix_maint_tech_area_user', table_name='maint_technician_areas')
    op.drop_index('ix_maint_tech_area_code', table_name='maint_technician_areas')
    op.drop_table('maint_technician_areas')
    op.drop_index('ix_maint_categories_active_order', table_name='maint_categories')
    op.drop_table('maint_categories')
    # ### end Alembic commands ###
