"""add_positions

Revision ID: edbc8ecae981
Revises: 9fa44de1aed0
Create Date: 2025-10-06 11:03:48.139127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbc8ecae981'
down_revision = '9fa44de1aed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_code'), ['code'], unique=True)

    op.create_table('position_app_roles',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'app_id', 'role_id')
    )
    with op.batch_alter_table('position_app_roles', schema=None) as batch_op:
        batch_op.create_index('ix_position_app_roles_position_app', ['position_id', 'app_id'], unique=False)

    op.create_table('program_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'program_id', name='uq_position_program')
    )
    with op.batch_alter_table('program_positions', schema=None) as batch_op:
        batch_op.create_index('ix_program_positions_position', ['position_id'], unique=False)
        batch_op.create_index('ix_program_positions_program', ['program_id'], unique=False)

    op.create_table('position_app_perms',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('perm_id', sa.Integer(), nullable=False),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perm_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'app_id', 'perm_id')
    )
    with op.batch_alter_table('position_app_perms', schema=None) as batch_op:
        batch_op.create_index('ix_position_app_perms_position_app', ['position_id', 'app_id'], unique=False)

    op.create_table('user_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'position_id', 'is_active', name='uq_active_user_position')
    )
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.create_index('ix_user_positions_active', ['user_id', 'position_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_positions_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_positions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_positions_position_id'))
        batch_op.drop_index('ix_user_positions_active')

    op.drop_table('user_positions')
    with op.batch_alter_table('position_app_perms', schema=None) as batch_op:
        batch_op.drop_index('ix_position_app_perms_position_app')

    op.drop_table('position_app_perms')
    with op.batch_alter_table('program_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_program_positions_program')
        batch_op.drop_index('ix_program_positions_position')

    op.drop_table('program_positions')
    with op.batch_alter_table('position_app_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_position_app_roles_position_app')

    op.drop_table('position_app_roles')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_code'))

    op.drop_table('positions')
    # ### end Alembic commands ###
