"""titulatec initial schema

Revision ID: f972f1db2ee5
Revises: 839300ac472a
Create Date: 2026-06-02 13:27:31.320635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f972f1db2ee5'
down_revision = '839300ac472a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titulatec_document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=True),
    sa.Column('file_kind', sa.String(length=10), server_default=sa.text("'pdf'"), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('is_versionable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_titulatec_document_types_is_active'), 'titulatec_document_types', ['is_active'], unique=False)
    op.create_table('titulatec_modalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('requires_synodals', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('signature_rule', sa.String(length=20), server_default=sa.text("'president_only'"), nullable=False),
    sa.Column('skips_phases', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_titulatec_modalities_is_active'), 'titulatec_modalities', ['is_active'], unique=False)
    op.create_table('titulatec_phase_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('responsible', sa.String(length=40), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_titulatec_phase_definitions_is_active'), 'titulatec_phase_definitions', ['is_active'], unique=False)
    op.create_table('titulatec_cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('opens_at', sa.Date(), nullable=True),
    sa.Column('closes_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['core_academic_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulatec_cohorts_period_id'), 'titulatec_cohorts', ['period_id'], unique=True)
    op.create_table('titulatec_ceremonies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('room', sa.String(length=60), nullable=True),
    sa.Column('whatsapp_group_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['titulatec_cohorts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulatec_ceremonies_cohort_id'), 'titulatec_ceremonies', ['cohort_id'], unique=False)
    op.create_table('titulatec_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('modality_id', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('is_app_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['titulatec_cohorts.id'], ),
    sa.ForeignKeyConstraint(['modality_id'], ['titulatec_modalities.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['core_programs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'cohort_id', name='uq_titulatec_process_student_cohort')
    )
    op.create_index(op.f('ix_titulatec_processes_cohort_id'), 'titulatec_processes', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_titulatec_processes_folio'), 'titulatec_processes', ['folio'], unique=True)
    op.create_index(op.f('ix_titulatec_processes_is_app_active'), 'titulatec_processes', ['is_app_active'], unique=False)
    op.create_index(op.f('ix_titulatec_processes_status'), 'titulatec_processes', ['status'], unique=False)
    op.create_index(op.f('ix_titulatec_processes_student_id'), 'titulatec_processes', ['student_id'], unique=False)
    op.create_table('titulatec_ceremony_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ceremony_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('final_project_path', sa.String(length=255), nullable=True),
    sa.Column('presentation_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['ceremony_id'], ['titulatec_ceremonies.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ceremony_id', 'process_id', name='uq_titulatec_ceremony_process')
    )
    op.create_index(op.f('ix_titulatec_ceremony_processes_ceremony_id'), 'titulatec_ceremony_processes', ['ceremony_id'], unique=False)
    op.create_index(op.f('ix_titulatec_ceremony_processes_process_id'), 'titulatec_ceremony_processes', ['process_id'], unique=False)
    op.create_table('titulatec_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('review_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'type_code', name='uq_titulatec_document_process_type')
    )
    op.create_index(op.f('ix_titulatec_documents_phase_number'), 'titulatec_documents', ['phase_number'], unique=False)
    op.create_index(op.f('ix_titulatec_documents_process_id'), 'titulatec_documents', ['process_id'], unique=False)
    op.create_table('titulatec_format_b',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('ext_number', sa.String(length=10), nullable=True),
    sa.Column('int_number', sa.String(length=10), nullable=True),
    sa.Column('control_number', sa.String(length=20), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('study_plan', sa.String(length=40), nullable=True),
    sa.Column('titulation_type', sa.String(length=60), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['core_programs.id'], ),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_table('titulatec_process_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulatec_process_events_created_at'), 'titulatec_process_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_titulatec_process_events_process_id'), 'titulatec_process_events', ['process_id'], unique=False)
    op.create_table('titulatec_process_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'phase_number', name='uq_titulatec_phase_process_number')
    )
    op.create_index(op.f('ix_titulatec_process_phases_process_id'), 'titulatec_process_phases', ['process_id'], unique=False)
    op.create_table('titulatec_review_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulatec_review_appointments_process_id'), 'titulatec_review_appointments', ['process_id'], unique=False)
    op.create_table('titulatec_synodal_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('vote', sa.String(length=20), nullable=True),
    sa.Column('vote_at', sa.DateTime(), nullable=True),
    sa.Column('vote_note', sa.Text(), nullable=True),
    sa.Column('assigned_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'user_id', name='uq_titulatec_synodal_process_user')
    )
    op.create_index(op.f('ix_titulatec_synodal_assignments_process_id'), 'titulatec_synodal_assignments', ['process_id'], unique=False)
    op.create_index(op.f('ix_titulatec_synodal_assignments_user_id'), 'titulatec_synodal_assignments', ['user_id'], unique=False)
    op.create_table('titulatec_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('pinned_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['pinned_document_id'], ['titulatec_documents.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['titulatec_processes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id')
    )
    op.create_table('titulatec_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['titulatec_chats.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['titulatec_chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulatec_chat_messages_chat_id'), 'titulatec_chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_titulatec_chat_messages_created_at'), 'titulatec_chat_messages', ['created_at'], unique=False)
    # NOTA: el resto de cambios que detectó autogenerate (índices/constraints de helpdesk_*)
    # son DRIFT de otras apps ajeno a TitulaTec y se removieron a propósito de esta migración.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titulatec_chat_messages_created_at'), table_name='titulatec_chat_messages')
    op.drop_index(op.f('ix_titulatec_chat_messages_chat_id'), table_name='titulatec_chat_messages')
    op.drop_table('titulatec_chat_messages')
    op.drop_table('titulatec_chats')
    op.drop_index(op.f('ix_titulatec_synodal_assignments_user_id'), table_name='titulatec_synodal_assignments')
    op.drop_index(op.f('ix_titulatec_synodal_assignments_process_id'), table_name='titulatec_synodal_assignments')
    op.drop_table('titulatec_synodal_assignments')
    op.drop_index(op.f('ix_titulatec_review_appointments_process_id'), table_name='titulatec_review_appointments')
    op.drop_table('titulatec_review_appointments')
    op.drop_index(op.f('ix_titulatec_process_phases_process_id'), table_name='titulatec_process_phases')
    op.drop_table('titulatec_process_phases')
    op.drop_index(op.f('ix_titulatec_process_events_process_id'), table_name='titulatec_process_events')
    op.drop_index(op.f('ix_titulatec_process_events_created_at'), table_name='titulatec_process_events')
    op.drop_table('titulatec_process_events')
    op.drop_table('titulatec_format_b')
    op.drop_index(op.f('ix_titulatec_documents_process_id'), table_name='titulatec_documents')
    op.drop_index(op.f('ix_titulatec_documents_phase_number'), table_name='titulatec_documents')
    op.drop_table('titulatec_documents')
    op.drop_index(op.f('ix_titulatec_ceremony_processes_process_id'), table_name='titulatec_ceremony_processes')
    op.drop_index(op.f('ix_titulatec_ceremony_processes_ceremony_id'), table_name='titulatec_ceremony_processes')
    op.drop_table('titulatec_ceremony_processes')
    op.drop_index(op.f('ix_titulatec_processes_student_id'), table_name='titulatec_processes')
    op.drop_index(op.f('ix_titulatec_processes_status'), table_name='titulatec_processes')
    op.drop_index(op.f('ix_titulatec_processes_is_app_active'), table_name='titulatec_processes')
    op.drop_index(op.f('ix_titulatec_processes_folio'), table_name='titulatec_processes')
    op.drop_index(op.f('ix_titulatec_processes_cohort_id'), table_name='titulatec_processes')
    op.drop_table('titulatec_processes')
    op.drop_index(op.f('ix_titulatec_ceremonies_cohort_id'), table_name='titulatec_ceremonies')
    op.drop_table('titulatec_ceremonies')
    op.drop_index(op.f('ix_titulatec_cohorts_period_id'), table_name='titulatec_cohorts')
    op.drop_table('titulatec_cohorts')
    op.drop_index(op.f('ix_titulatec_phase_definitions_is_active'), table_name='titulatec_phase_definitions')
    op.drop_table('titulatec_phase_definitions')
    op.drop_index(op.f('ix_titulatec_modalities_is_active'), table_name='titulatec_modalities')
    op.drop_table('titulatec_modalities')
    op.drop_index(op.f('ix_titulatec_document_types_is_active'), table_name='titulatec_document_types')
    op.drop_table('titulatec_document_types')
    # ### end Alembic commands ###
